### ISSUE TITLE
author tag causes ament_xmllint to fail

### ISSUE THREAD

**Issue by wmmc88** [ament/ament_lint#348]
I suspect other optional tags cause it to fail as well.

```
(bash) ~ 
❯ ament_xmllint package.xml 
File 'package.xml' is invalid:
/home/wmmc88/package.xml:9: element author: Schemas validity error : Element 'author': This element is not expected. Expected is one of ( maintainer, license ).
/home/wmmc88/package.xml fails to validate

1 files are invalid
```

`package.xml`
```
<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>test_pkg</name>
  <version>0.0.0</version>
  <description>This is a package description</description>

  <maintainer email="abc@def.com">John</maintainer>
  <author email="abc@def.com">Jane</author>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>another_pkg</exec_depend>

  <test_depend>ament_cmake_xmllint</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
```

**Comment by aprotyas** [comment]
I believe this is more a talking point about the [package manifest schema](https://github.com/ros-infrastructure/rep/blob/master/xsd/package_format3.xsd) than it is a problem with `ament_xmllint`, since this tool just redirects the verification against the linked schema to the `xmllint` binary.

The schema uses the [`xs:sequence`](http://www.w3.org/TR/xmlschema11-1/#element-sequence) indicator for all children of the `package` tag, i.e. the children tags are ordered in the order specified in the schema. I don't know the reasoning behind "order matters" in the package manifest, but from my experience with XML, unordered lists have occurrence restrictions - for example, for XSD 1.0, ordered child elements can not have unbounded occurrence; you can see how this would be a problem for the dependency tags.

**Comment by wmmc88** [comment]
Ah. I had missed the xs:sequence tag when I skimmed through the schema. Putting the author tags after license does indeed fix my issues. Thanks!

**Comment by christophebedard** [comment]
I hit this (pretty minor) issue in the past as well.

> Finally, this could probably be documented better in [REP 149 (Package Manifest Format Three Specification)](https://www.ros.org/reps/rep-0149.html).

Agreed!

Also, the error message *could* be a little more helpful (e.g., suggest that the elements are valid but that the order is simply wrong), but I'm guessing that it probably comes from the XML parser itself.
