### ISSUE TITLE
backport fixes and features to non-EOL distros

### ISSUE THREAD

**Issue by wmmc88** [ament/ament_lint#349]
I was looking at index.ros.org and noticed that the latest version available for foxy(ie. the latest stable ros distro) is `0.9.6` and the latest for galactic(ie. the latest ros distro) is `0.10.6`, while the latest rolling version is `0.11.4`.

Is there any plans to make new releases to distros that are not EOL? There are features that I'd like to use in galactic packages such as #331

**Comment by aprotyas** [comment]
I think you can open backport PRs for the ones you're interested in.

**Comment by wmmc88** [comment]
Is there any reason why new releases from master aren't just sent to galactic, foxy and rolling? 

Sidenote: I noticed some other ros repos tend to use the mergify plugin to simplify backporting of patches to all the non-eol distro branches. this makes so that the branches don't diverge as much.

**Comment by aprotyas** [comment]
> Is there any reason why new releases from master aren't just sent to galactic, foxy and rolling?

I'm not sure about the process. I'll defer that question to the repo maintainers..

> Sidenote: I noticed some other ros repos tend to use the mergify plugin to simplify backporting of patches to all the non-eol distro branches. this makes so that the branches don't diverge as much.

I think mergify is also configured for the `ament` org, but we'd need someone with write access to run it.

**Comment by clalancette** [comment]
> Is there any reason why new releases from master aren't just sent to galactic, foxy and rolling?

Yes.  We aim for very tight backwards compatibility in our stable releases.  So we tend to only release things that people are having issues with on the older releases.  Even then, we often have to rewrite them to keep backwards compatibility.  That gives us the ability to make more breaking changes on the master branches.

If there are particular issues or features that you'd like to see, we are happy to review backport PRs.

I'm going to close this out because this is more of a question than an issue, but feel free to keep commenting.
