### ISSUE TITLE
[ament_pep257] ament_pep257 not showing errors as stderr

### ISSUE THREAD

**Issue by mikramarc** [ament/ament_lint#389]
Currently when running ament_pep257 command all the errors are shown as regular stdout output. This make's it hard to handle the errors, log correctly, visualize easily, etc. Seems like other loggers in ament do have that feature (i.e. actually outputting errors to stderr). Is there any desire/plan to change that anytime soon?

**Comment by com2rng** [comment]
@dirk-thomas (I suppose you are the maintainer of this repo, or at least the one with the largest amount of commits) since this issue happens in both master and foxy branches -- the latter I'm currently using--, how can we deal with this issue?
I'm actually working with the boschresearch group and planning to contribute this fix back. 
Shall I create two different PR for fixes in master and foxy or is there a plan to update foxy to master soon?
