### ISSUE TITLE
ament_lint_clang_tidy: not recognizing 'csignal' header

### ISSUE THREAD

**Issue by caioaamaral** [ament/ament_lint#504]
While running `ament_clang_tidy` on my compile_commands.json, I got the following error:

```console
/opt/ros/humble/include/rclcpp/rclcpp/rclcpp.hpp:152:10: error: 'csignal' file not found [clang-diagnostic-error]
#include <csignal>
```

`csignal` is a standard library header, it should be recognized. Not sure if the problem is within clang-tidy library

**Comment by caioaamaral** [comment]
probably related to https://www.lidavidm.me/c++/2023/06/16/c++-clang-tidy-complains-it-can-t-find-common-headers-especially-under-conda-conda-forge.html

**Comment by cottsay** [comment]
With the information here, this doesn't seem like a bug in `ament_lint`.

Feel free to re-open this issue if you can describe how this might be addressed with a change to `ament_lint`, otherwise I think asking for help on the [Robotics Stack Exchange](https://robotics.stackexchange.com/) might be more likely to lead to a solution.
