### ISSUE TITLE
clang_format line references are incorrect

### ISSUE THREAD

**Issue by tfoote** [ament/ament_lint#6]
[This file](https://github.com/ros2/rosidl/blob/master/rosidl_generator_c/include/rosidl_generator_c/arrays.h) has 124 lines, but it's citing line 5529. 

http://54.183.26.131:8080/job/ros2_batch_ci/lastCompletedBuild/testReport/%28root%29/replacement/__include_rosidl_generator_c_arrays_h_5529/
```
replacement../include/rosidl_generator_c/arrays.h:5529 (from clang_format)
Failing for the past 1 build (Since Unstable#83 )
Took 0 ms.
Stacktrace

Replace 81 characters with [         \\n    ]
```

**Comment by dirk-thomas** [comment]
The index in your output refers to the byte offset in the file.

This has already been improved in 2b77c91ca6e9a6733086b1e7ec9ccaa3c6ed17a5 which converts the global offset into a line number and offset-in-line.

**Comment by dirk-thomas** [comment]
The output of the unit tests already does the conversion but the written xml file does still use global offsets.

**Comment by dirk-thomas** [comment]
Since I had to test this with the CI job I didn't go through a PR: https://github.com/ament/ament_lint/commit/b63016d24bc89a3f359f98fe8bd66438b68670e1

Output before: http://54.183.26.131:8080/job/ros2_batch_ci/91/testReport/(root)/replacement/__include_rcl_rcl_h_718/

Output now: http://54.183.26.131:8080/job/ros2_batch_ci/lastCompletedBuild/testReport/(root)/replacement/__include_rcl_rcl_h_20_19/

@esteve @tfoote @wjwwood FYI
