### ISSUE TITLE
Add in support for the BSD license in the copyright linting

### ISSUE THREAD

**Issue by clalancette** [ament/ament_lint#72]
Some of the code that is coming into the codebase originally came from ROS1 with a BSD license.  Since we are not making substantial changes to it, we can't really change the license (see https://github.com/ros2/common_interfaces/commit/025b1911ab2b135ea009017b06069a88e7e05817#commitcomment-21888534 for a discussion on this).

However, we would like to lint these files.  To do this, I think we'll have to add support for the BSD copyright into ament_lint.  For an example of it failing, see: http://ci.ros2.org/job/ci_linux/2531/ , where the failing file is https://github.com/ros2/common_interfaces/blob/master/sensor_msgs/include/sensor_msgs/distortion_models.hpp

**Comment by mikaelarguedas** [comment]
For reference this related to https://github.com/ament/ament_lint/pull/66 and https://github.com/ament/ament_lint/issues/65

**Comment by dirk-thomas** [comment]
You can add new licenses by registering a new license as an entry point: https://github.com/ament/ament_lint/blob/6c7a0ab90b8c620d4e6f28cb5a56254f065f48a1/ament_copyright/setup.py#L34

I don't think it is related to the referenced tickets since you want it to support BSD - not packages with multiple licenses.

**Comment by clalancette** [comment]
Closing since #73 was closed.
