### ISSUE TITLE
ament_test fails on ament_uncrustify 

### ISSUE THREAD

**Issue by jpsamper2009** [ament/ament_lint#91]
## Description
- ament_uncrustify is failing: http://ci.ros2.org/job/ci_linux/3854/consoleFull#console-section-236. 
- My guess is that since there are no tests, the coverage script complains and returns with exit code 5. Since the `ament test` call ignores return codes, this error is not caught.

## Proposed solution
- It is possible to hide this error by adding any test. For example, if you add a simple test_copyright.py, tests will pass.
- Nevertheless, there seems to be some inconsistency where some packages are allowed to have zero tests while other packages fail on zero tests (for example, `ament_lint_common` will pass even though it has no tests.

**Comment by dirk-thomas** [comment]
I have tried to reproduce the same in the new build tool I am working on in my spare time and couldn't get it to behave the same way. Since my expectation is that `ament_tools` will be replaced within this release cycle I won't spend any time debugging the issue in `ament_tools`.

Maybe someone else wants to investigate the problem and propose a fix for it.

**Comment by mikaelarguedas** [comment]
@jpsamper2009 if this is not a blocker for you, I'm going to put this back in backlog as we are not planning on iterating on `ament_tools` at the moment.
Feel free to keep commenting on this or to submit a PR to address the issue

**Comment by jpsamper2009** [comment]
@mikaelarguedas @dirk-thomas I think we can close this issue since it's based on `ament_tools` which has been depreacted as far as I know.
